### PR TITLE
Changed BitCoin to Bitcoin

### PR DESCRIPTION
**Pull request by feulf**

### CODE REVIEW

**Comment by Heeroyuy8** [comment]
If I buy one Account of you. withdraw on my bank under my name got any problem?

**Comment by Heeroyuy8** [comment]
email me at heeroyuy@mail.com

**Comment by fenrisdarko** [comment]
PLease email to fenrisdarko@yahoo.com I bought an account and it went through 7 confirmations yet I never recieved the account info. When I went back to the board I noticed the account I tried to buy was back on for purchase. Please fix this.

**Comment by kypluk1** [comment]
I bought an account on Phantomteam1@yandex.com mail but I have not received a letter. Please, help.

**Comment by butler007** [comment]
slt bro

**Comment by jahajjahaj** [comment]
or anyone frome ks al srb ??

**Pull request merged**
